# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e8ed3efecb66fc9b64e832c3562ff7aa78526e302702d4e25d728d6875c326e94a11576989632d435aa9d0e6ec29a94334e7d7d7c6880c9944a0b4ac53a17e3

test:
  secret_key_base: b42e779618de7ec71644597d3f6c912c5d65cbbfe08cda162eb2e4022af8b6569464dc08c529b56b8da14008276e514d19614bf6e62583e712ad9b76b38da16f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
